<?php
	
	namespace Database\Seeders;
	
	use App\Models\Banks;
	use Faker\Generator;
	use Illuminate\Database\Seeder;
	
	class BankSeeder extends Seeder
	{
		public function run(Generator $faker)
		{
			Banks::create([
				'id' => null,
				'name' => 'vietcombank',
				'full_name' => 'vietcombank',
				'desc' => 'vietcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'techcombank',
				'full_name' => 'techcombank',
				'desc' => 'techcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'vietcombank',
				'full_name' => 'vietcombank',
				'desc' => 'vietcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Dong A',
				'full_name' => 'Dong A',
				'desc' => 'Dong A',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Saccombank',
				'full_name' => 'Saccombank',
				'desc' => 'Saccombank',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Nam A',
				'full_name' => 'Nam A',
				'desc' => 'Nam A',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Bac A',
				'full_name' => 'Bac A',
				'desc' => 'Bac A',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'techcombank',
				'full_name' => 'techcombank',
				'desc' => 'techcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'vietcombank',
				'full_name' => 'vietcombank',
				'desc' => 'vietcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'vietcombank',
				'full_name' => 'vietcombank',
				'desc' => 'vietcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'techcombank',
				'full_name' => 'techcombank',
				'desc' => 'techcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'vietcombank',
				'full_name' => 'vietcombank',
				'desc' => 'vietcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Dong A',
				'full_name' => 'Dong A',
				'desc' => 'Dong A',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Saccombank',
				'full_name' => 'Saccombank',
				'desc' => 'Saccombank',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Nam A',
				'full_name' => 'Nam A',
				'desc' => 'Nam A',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'Bac A',
				'full_name' => 'Bac A',
				'desc' => 'Bac A',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'techcombank',
				'full_name' => 'techcombank',
				'desc' => 'techcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
			
			Banks::create([
				'id' => null,
				'name' => 'vietcombank',
				'full_name' => 'vietcombank',
				'desc' => 'vietcombank banks',
				'branch' => 'Ho Chi Minh City',
				'number1' => '093 323 234 2342',
				'number2' => '43243324234',
				'port' => 3306,
				'url' => 'https://toidicodedao.click',
				'username' => 'demo',
				'password' => 'demo',
				'desc_api' => 'desc api',
				'customfields1' => 'No Data',
				'customfields2' => 'No Data',
				'customfields3' => 'No Data',
				'customfields4' => 'No Data',
				'customfields5' => 'No Data',
			]);
		}
		
		
	}
